version: "3.6"

services:

  ubuntu-test:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu.test
    working_dir: /workspace
#    command: apt-get install -y chaossystems-devtools
    command: /bin/bash
    tty: true
    stdin_open: true
