version: "3.6"

services:
  build:
    build:
      context: .
      dockerfile: Dockerfile.build
    working_dir: /build
    volumes:
      - .:/build:rw

  rpm-test:
    image: fedora:latest
    working_dir: /rpm-build
    volumes:
      - .:/rpm-build:rw

  ubuntu-test:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu.test
    working_dir: /workspace
#    command: apt-get install -y chaossystems-devtools
    command: /bin/bash
    tty: true
    stdin_open: true
