FROM ubuntu:rolling

RUN apt-get update \
    && apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common lsb-release \
    && curl -fsSL https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/gpg | (OUT=$(apt-key add - 2>&1) || echo $OUT) \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]') $(lsb_release -cs) stable" \
    && curl -fsSL https://apt.cha0s.dev/pub.gpg | (OUT=$(apt-key add - 2>&1) || echo $OUT) \
    && echo "deb https://apt.cha0s.dev stable main" | tee -a /etc/apt/sources.list.d/chaos-dev.list \
    && apt-get update \
    && apt-get install -y chaossystems-cli \
