FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y ca-certificates gnupg2 && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61 && \
    echo "deb https://dl.bintray.com/chaos-systems/deb bionic main" | tee -a /etc/apt/sources.list
